### ISSUE TITLE
Encoding in der Konsole macht komische Dinge

### ISSUE THREAD

**Issue by haqfleisch** [pfackeldey/PineBanana#3]
In der Konsole werden Umlaute als UTF-8 Chars escaped. Entweder ich bin ganz dumm oder das sollte zumindest für Umlaute nicht der Fall sein.

Im TXT ist aber alles wie soll.

**Comment by pfackeldey** [comment]
Hab mal in die txt geschaut. Smileys und sowas machen ein bisschen was kaputt. Müssen wir mal schauen ob das netzwrk sowas kann.
Du kannst einfach mit der folgenden umgebungsvariablen checken wie dein encoding im terminal ist:
```
$ echo $LC_CTYPE
```
Du kannst dir auch noch die language ausgeben lassen mit:
```
$ echo $LANG
$ locale -a 
```
um utf-8 coding dann zu benutzen kannst du ja einfach mit "export" das utf-8 encoding an deine umgebungsvariable dran setzen

**Comment by haqfleisch** [comment]
Hab den Bösewicht gefunden... Die Ausgabe in die Konsole erfolgt natürlich über den einen Aufruf den ich noch nicht encoded habe.

getweet.py l.50. Fixe ich beizeiten...

**Comment by haqfleisch** [comment]
funzt jetzt soweit alles.
